// export const CROWDLOAN_ENDPOINT = 'wss://rpc.polkadot.io';
// export const CROWDLOAN_ENDPOINT = 'wss://osaka.astar.network';
export const CROWDLOAN_ENDPOINT = 'wss://kusama-rpc.polkadot.io';
export const PARA_ID = 2000;
// export const PARA_ID = 2120;
export const MINIMUM_STAKING_AMOUNT = 1;
export const REWARD_RATIO = 24.4;
export const MIN_BALANCE = 0.01;
export const UNIT = 12; // kusama unit
